version: "3.8"

x-django-env: &django-env
  DJANGO_DATABASE_NAME: postgres
  DJANGO_DATABASE_USER: postgres
  DJANGO_DATABASE_PASSWORD: postgres
  DJANGO_DATABASE_HOST: db
  DJANGO_DATABASE_PORT: 5432

x-db-env: &db-env
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

services:
  react:
    build: frontend
    command: yarn start
    volumes:
      - "./frontend/src:/app/src"
      - "./frontend/package.json:/app/package.json"
      - "./frontend/yarn.lock:/app/yarn.lock"
    ports:
      - 3000:3000

  db:
    image: "postgres:12"
    environment: *db-env
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    ports:
      - 5432:5432

  web:
    build: backend
    volumes:
      - "./backend:/app"
    environment: *django-env
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres-data: