version: "3.8"

x-db-env: &db-env
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

services:
  react:
    build: frontend
    command: yarn start
    volumes:
      - "./frontend/src:/app/src"
    ports:
      - "127.0.0.1:3000:3000"

  db:
    image: postgres
    environment: *db-env
    ports:
      - 5432:5432

  web:
    build: backend
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - "./backend:/app"
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db
    network_mode: host
    restart: on-failure